ARG NODE_VERSION=21.5.0
FROM node:${NODE_VERSION} as base

WORKDIR /app

COPY package*.json ./
RUN npm install

ARG NEXT_PUBLIC_DOMAIN
# ENV NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN

ARG NEXT_PUBLIC_API_URL
# ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_SOCKET_SERVER_URL
# ENV NEXT_PUBLIC_SOCKET_SERVER_URL=$NEXT_PUBLIC_SOCKET_SERVER_URL

COPY . .

RUN echo "NEXT_PUBLIC_DOMAIN='$NEXT_PUBLIC_DOMAIN'" >> .env
RUN echo "NEXT_PUBLIC_API_URL='$NEXT_PUBLIC_API_URL'" >> .env
RUN echo "NEXT_PUBLIC_SOCKET_SERVER_URL='$NEXT_PUBLIC_SOCKET_SERVER_URL'" >> .env

RUN npm run build

# Expose the listening port
EXPOSE 3000

# Run npm start command
CMD [ "npm", "start" ]
